### ISSUE TITLE
SSH error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jaedb** [springload/ecs-tool#13]
- ecs-tool version 1.5.1
- Ubuntu 18.04

Credentials etc are all correct as I can execute other calls (eg `ecs-tool run -e production -- uptime`) with no issue.

However when attempting to connect SSH, I get the following error:
```
$ ecs-tool ssh -e production
  INFO[0000] Using config file: /XXX/infra/ecs-production.toml
  INFO[0000] Looking for ECS Task...   task_definition=XXX-production-app
  INFO[0000] Looking for EC2 Instance... task_arn=XXX:XXX task_definition=XXX-production-app
  INFO[0001] Pushing SSH key...        instance_id=XXX task_definition=XXX-production-app
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xc8d9ca]

goroutine 1 [running]:
golang.org/x/crypto/ssh/agent.(*client).callRaw(0xc0004d9bc0, 0xc00010d9fb, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/ekini/go/pkg/mod/golang.org/x/crypto@v0.0.0-20190701094942-4def268fd1a4/ssh/agent/client.go:341 +0x13a
golang.org/x/crypto/ssh/agent.(*client).call(0xc0004d9bc0, 0xc00010d9fb, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc00010da18)
        /Users/ekini/go/pkg/mod/golang.org/x/crypto@v0.0.0-20190701094942-4def268fd1a4/ssh/agent/client.go:320 +0x50
golang.org/x/crypto/ssh/agent.(*client).List(0xc0004d9bc0, 0xc0004d9bc0, 0x0, 0x0, 0x0, 0x0)
        /Users/ekini/go/pkg/mod/golang.org/x/crypto@v0.0.0-20190701094942-4def268fd1a4/ssh/agent/client.go:402 +0x56
github.com/springload/ecs-tool/lib.ConnectSSH(0xc000099110, 0x6, 0xc00009b2a0, 0x11, 0xc00009b340, 0x15, 0xc0000994e0, 0x3, 0xc0000994b4, 0x2, ...)
        /Users/ekini/springload/ecs-tool/lib/ssh.go:92 +0x948
github.com/springload/ecs-tool/cmd.glob..func7(0x1cc48e0, 0xc0000abe60, 0x0, 0x2)
        /Users/ekini/springload/ecs-tool/cmd/ssh.go:22 +0x293
github.com/spf13/cobra.(*Command).execute(0x1cc48e0, 0xc0000abde0, 0x2, 0x2, 0x1cc48e0, 0xc0000abde0)
        /Users/ekini/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x1cc4420, 0x1cc48e0, 0xc000131f20, 0x43b60a)
        /Users/ekini/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/ekini/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/springload/ecs-tool/cmd.Execute(0x140edd8, 0x5)
        /Users/ekini/springload/ecs-tool/cmd/root.go:34 +0x5d
main.main()
        /Users/ekini/springload/ecs-tool/main.go:8 +0x39
```

**Comment by ekini** [comment]
I think I know why. Could you please try 1.5.3 version?

**Comment by johnanders123** [comment]
There's been a change to this on 1.5.3 the reporter is now getting:

 ERROR[0000] Can't connect to the ssh agent error=dial unix: missing address task_definition=cowapi-dev-app
 ERROR[0000] Can't execute ssh         error=dial unix: missing address

**Comment by ekini** [comment]
Nice, it means `SSH_AUTH_SOCK` env var is not set, and that means ssh-agent is not configured.

**Comment by johnanders123** [comment]
Confirmed it's all fixed @ekini :)
